server {
    listen 3000;
    server_name localhost bengalurusmarttrafficnavigator.com;

    # Emulate SPA behaviors by proxying 404s implicitly to index.html resolving internal React Route definitions
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
